package uhx.sys.seri.v::pack::;

/**
    ------
    DO NOT EDIT THIS FILE
    ------
    This file has be auto-generated.
**/

import uhx.sys.seri.Range;
import uhx.sys.seri.Single;
import uhx.sys.seri.Ranges;

@:unicode("::version::")
enum abstract ::typeName::(String) {
    ::foreach fields::
    ::if define:: #if ::define:: ::end::public var ::ident:: = "::value::";::if define:: #end ::end::::end::

    public static inline function all():Array<::typeName::> return [::foreach fields::
        ::if define::#if ::define::::end::::ident::, ::if define::#end::end::::end::
    ];

    @:to public inline function asRange():::rangeType:: {
        return switch this {
            #if !display
            ::foreach fields::
            ::if define::#if ::define::::end::case ::ident:::
                ::range::;
            ::if define::#end::end::::end::
            #end
            case _:
                ::rangeType::.EMPTY;
        }
    }
}