package uhx.sys.seri.v900;

/**
    ------
    DO NOT EDIT THIS FILE
    ------
    This file has be auto-generated.
**/

import uhx.sys.seri.Range;
import uhx.sys.seri.Ranges;

@:unicode("9.0.0")
enum abstract Block(String) {
    
    public var BasicLatin = "Basic Latin";
    public var Latin1Supplement = "Latin-1 Supplement";
    public var LatinExtendedA = "Latin Extended-A";
    public var LatinExtendedB = "Latin Extended-B";
    public var IPAExtensions = "IPA Extensions";
    public var SpacingModifierLetters = "Spacing Modifier Letters";
    public var CombiningDiacriticalMarks = "Combining Diacritical Marks";
    public var GreekAndCoptic = "Greek and Coptic";
    public var Cyrillic = "Cyrillic";
    public var CyrillicSupplement = "Cyrillic Supplement";
    public var Armenian = "Armenian";
    public var Hebrew = "Hebrew";
    public var Arabic = "Arabic";
    public var Syriac = "Syriac";
    public var ArabicSupplement = "Arabic Supplement";
    public var Thaana = "Thaana";
    public var NKo = "NKo";
    public var Samaritan = "Samaritan";
    public var Mandaic = "Mandaic";
    public var ArabicExtendedA = "Arabic Extended-A";
    public var Devanagari = "Devanagari";
    public var Bengali = "Bengali";
    public var Gurmukhi = "Gurmukhi";
    public var Gujarati = "Gujarati";
    public var Oriya = "Oriya";
    public var Tamil = "Tamil";
    public var Telugu = "Telugu";
    public var Kannada = "Kannada";
    public var Malayalam = "Malayalam";
    public var Sinhala = "Sinhala";
    public var Thai = "Thai";
    public var Lao = "Lao";
    public var Tibetan = "Tibetan";
    public var Myanmar = "Myanmar";
    public var Georgian = "Georgian";
    public var HangulJamo = "Hangul Jamo";
    public var Ethiopic = "Ethiopic";
    public var EthiopicSupplement = "Ethiopic Supplement";
    public var Cherokee = "Cherokee";
    public var UnifiedCanadianAboriginalSyllabics = "Unified Canadian Aboriginal Syllabics";
    public var Ogham = "Ogham";
    public var Runic = "Runic";
    public var Tagalog = "Tagalog";
    public var Hanunoo = "Hanunoo";
    public var Buhid = "Buhid";
    public var Tagbanwa = "Tagbanwa";
    public var Khmer = "Khmer";
    public var Mongolian = "Mongolian";
    public var UnifiedCanadianAboriginalSyllabicsExtended = "Unified Canadian Aboriginal Syllabics Extended";
    public var Limbu = "Limbu";
    public var TaiLe = "Tai Le";
    public var NewTaiLue = "New Tai Lue";
    public var KhmerSymbols = "Khmer Symbols";
    public var Buginese = "Buginese";
    public var TaiTham = "Tai Tham";
    public var CombiningDiacriticalMarksExtended = "Combining Diacritical Marks Extended";
    public var Balinese = "Balinese";
    public var Sundanese = "Sundanese";
    public var Batak = "Batak";
    public var Lepcha = "Lepcha";
    public var OlChiki = "Ol Chiki";
    public var CyrillicExtendedC = "Cyrillic Extended-C";
    public var SundaneseSupplement = "Sundanese Supplement";
    public var VedicExtensions = "Vedic Extensions";
    public var PhoneticExtensions = "Phonetic Extensions";
    public var PhoneticExtensionsSupplement = "Phonetic Extensions Supplement";
    public var CombiningDiacriticalMarksSupplement = "Combining Diacritical Marks Supplement";
    public var LatinExtendedAdditional = "Latin Extended Additional";
    public var GreekExtended = "Greek Extended";
    public var GeneralPunctuation = "General Punctuation";
    public var SuperscriptsAndSubscripts = "Superscripts and Subscripts";
    public var CurrencySymbols = "Currency Symbols";
    public var CombiningDiacriticalMarksForSymbols = "Combining Diacritical Marks for Symbols";
    public var LetterlikeSymbols = "Letterlike Symbols";
    public var NumberForms = "Number Forms";
    public var Arrows = "Arrows";
    public var MathematicalOperators = "Mathematical Operators";
    public var MiscellaneousTechnical = "Miscellaneous Technical";
    public var ControlPictures = "Control Pictures";
    public var OpticalCharacterRecognition = "Optical Character Recognition";
    public var EnclosedAlphanumerics = "Enclosed Alphanumerics";
    public var BoxDrawing = "Box Drawing";
    public var BlockElements = "Block Elements";
    public var GeometricShapes = "Geometric Shapes";
    public var MiscellaneousSymbols = "Miscellaneous Symbols";
    public var Dingbats = "Dingbats";
    public var MiscellaneousMathematicalSymbolsA = "Miscellaneous Mathematical Symbols-A";
    public var SupplementalArrowsA = "Supplemental Arrows-A";
    public var BraillePatterns = "Braille Patterns";
    public var SupplementalArrowsB = "Supplemental Arrows-B";
    public var MiscellaneousMathematicalSymbolsB = "Miscellaneous Mathematical Symbols-B";
    public var SupplementalMathematicalOperators = "Supplemental Mathematical Operators";
    public var MiscellaneousSymbolsAndArrows = "Miscellaneous Symbols and Arrows";
    public var Glagolitic = "Glagolitic";
    public var LatinExtendedC = "Latin Extended-C";
    public var Coptic = "Coptic";
    public var GeorgianSupplement = "Georgian Supplement";
    public var Tifinagh = "Tifinagh";
    public var EthiopicExtended = "Ethiopic Extended";
    public var CyrillicExtendedA = "Cyrillic Extended-A";
    public var SupplementalPunctuation = "Supplemental Punctuation";
    public var CJKRadicalsSupplement = "CJK Radicals Supplement";
    public var KangxiRadicals = "Kangxi Radicals";
    public var IdeographicDescriptionCharacters = "Ideographic Description Characters";
    public var CJKSymbolsAndPunctuation = "CJK Symbols and Punctuation";
    public var Hiragana = "Hiragana";
    public var Katakana = "Katakana";
    public var Bopomofo = "Bopomofo";
    public var HangulCompatibilityJamo = "Hangul Compatibility Jamo";
    public var Kanbun = "Kanbun";
    public var BopomofoExtended = "Bopomofo Extended";
    public var CJKStrokes = "CJK Strokes";
    public var KatakanaPhoneticExtensions = "Katakana Phonetic Extensions";
    public var EnclosedCJKLettersAndMonths = "Enclosed CJK Letters and Months";
    public var CJKCompatibility = "CJK Compatibility";
    public var CJKUnifiedIdeographsExtensionA = "CJK Unified Ideographs Extension A";
    public var YijingHexagramSymbols = "Yijing Hexagram Symbols";
    public var CJKUnifiedIdeographs = "CJK Unified Ideographs";
    public var YiSyllables = "Yi Syllables";
    public var YiRadicals = "Yi Radicals";
    public var Lisu = "Lisu";
    public var Vai = "Vai";
    public var CyrillicExtendedB = "Cyrillic Extended-B";
    public var Bamum = "Bamum";
    public var ModifierToneLetters = "Modifier Tone Letters";
    public var LatinExtendedD = "Latin Extended-D";
    public var SylotiNagri = "Syloti Nagri";
    public var CommonIndicNumberForms = "Common Indic Number Forms";
    public var PhagsPa = "Phags-pa";
    public var Saurashtra = "Saurashtra";
    public var DevanagariExtended = "Devanagari Extended";
    public var KayahLi = "Kayah Li";
    public var Rejang = "Rejang";
    public var HangulJamoExtendedA = "Hangul Jamo Extended-A";
    public var Javanese = "Javanese";
    public var MyanmarExtendedB = "Myanmar Extended-B";
    public var Cham = "Cham";
    public var MyanmarExtendedA = "Myanmar Extended-A";
    public var TaiViet = "Tai Viet";
    public var MeeteiMayekExtensions = "Meetei Mayek Extensions";
    public var EthiopicExtendedA = "Ethiopic Extended-A";
    public var LatinExtendedE = "Latin Extended-E";
    public var CherokeeSupplement = "Cherokee Supplement";
    public var MeeteiMayek = "Meetei Mayek";
    public var HangulSyllables = "Hangul Syllables";
    public var HangulJamoExtendedB = "Hangul Jamo Extended-B";
    public var HighSurrogates = "High Surrogates";
    public var HighPrivateUseSurrogates = "High Private Use Surrogates";
    public var LowSurrogates = "Low Surrogates";
    public var PrivateUseArea = "Private Use Area";
    public var CJKCompatibilityIdeographs = "CJK Compatibility Ideographs";
    public var AlphabeticPresentationForms = "Alphabetic Presentation Forms";
    public var ArabicPresentationFormsA = "Arabic Presentation Forms-A";
    public var VariationSelectors = "Variation Selectors";
    public var VerticalForms = "Vertical Forms";
    public var CombiningHalfMarks = "Combining Half Marks";
    public var CJKCompatibilityForms = "CJK Compatibility Forms";
    public var SmallFormVariants = "Small Form Variants";
    public var ArabicPresentationFormsB = "Arabic Presentation Forms-B";
    public var HalfwidthAndFullwidthForms = "Halfwidth and Fullwidth Forms";
    public var Specials = "Specials";
    public var LinearBSyllabary = "Linear B Syllabary";
    public var LinearBIdeograms = "Linear B Ideograms";
    public var AegeanNumbers = "Aegean Numbers";
    public var AncientGreekNumbers = "Ancient Greek Numbers";
    public var AncientSymbols = "Ancient Symbols";
    public var PhaistosDisc = "Phaistos Disc";
    public var Lycian = "Lycian";
    public var Carian = "Carian";
    public var CopticEpactNumbers = "Coptic Epact Numbers";
    public var OldItalic = "Old Italic";
    public var Gothic = "Gothic";
    public var OldPermic = "Old Permic";
    public var Ugaritic = "Ugaritic";
    public var OldPersian = "Old Persian";
    public var Deseret = "Deseret";
    public var Shavian = "Shavian";
    public var Osmanya = "Osmanya";
    public var Osage = "Osage";
    public var Elbasan = "Elbasan";
    public var CaucasianAlbanian = "Caucasian Albanian";
    public var LinearA = "Linear A";
    public var CypriotSyllabary = "Cypriot Syllabary";
    public var ImperialAramaic = "Imperial Aramaic";
    public var Palmyrene = "Palmyrene";
    public var Nabataean = "Nabataean";
    public var Hatran = "Hatran";
    public var Phoenician = "Phoenician";
    public var Lydian = "Lydian";
    public var MeroiticHieroglyphs = "Meroitic Hieroglyphs";
    public var MeroiticCursive = "Meroitic Cursive";
    public var Kharoshthi = "Kharoshthi";
    public var OldSouthArabian = "Old South Arabian";
    public var OldNorthArabian = "Old North Arabian";
    public var Manichaean = "Manichaean";
    public var Avestan = "Avestan";
    public var InscriptionalParthian = "Inscriptional Parthian";
    public var InscriptionalPahlavi = "Inscriptional Pahlavi";
    public var PsalterPahlavi = "Psalter Pahlavi";
    public var OldTurkic = "Old Turkic";
    public var OldHungarian = "Old Hungarian";
    public var RumiNumeralSymbols = "Rumi Numeral Symbols";
    public var Brahmi = "Brahmi";
    public var Kaithi = "Kaithi";
    public var SoraSompeng = "Sora Sompeng";
    public var Chakma = "Chakma";
    public var Mahajani = "Mahajani";
    public var Sharada = "Sharada";
    public var SinhalaArchaicNumbers = "Sinhala Archaic Numbers";
    public var Khojki = "Khojki";
    public var Multani = "Multani";
    public var Khudawadi = "Khudawadi";
    public var Grantha = "Grantha";
    public var Newa = "Newa";
    public var Tirhuta = "Tirhuta";
    public var Siddham = "Siddham";
    public var Modi = "Modi";
    public var MongolianSupplement = "Mongolian Supplement";
    public var Takri = "Takri";
    public var Ahom = "Ahom";
    public var WarangCiti = "Warang Citi";
    public var PauCinHau = "Pau Cin Hau";
    public var Bhaiksuki = "Bhaiksuki";
    public var Marchen = "Marchen";
    public var Cuneiform = "Cuneiform";
    public var CuneiformNumbersAndPunctuation = "Cuneiform Numbers and Punctuation";
    public var EarlyDynasticCuneiform = "Early Dynastic Cuneiform";
    public var EgyptianHieroglyphs = "Egyptian Hieroglyphs";
    public var AnatolianHieroglyphs = "Anatolian Hieroglyphs";
    public var BamumSupplement = "Bamum Supplement";
    public var Mro = "Mro";
    public var BassaVah = "Bassa Vah";
    public var PahawhHmong = "Pahawh Hmong";
    public var Miao = "Miao";
    public var IdeographicSymbolsAndPunctuation = "Ideographic Symbols and Punctuation";
    public var Tangut = "Tangut";
    public var TangutComponents = "Tangut Components";
    public var KanaSupplement = "Kana Supplement";
    public var Duployan = "Duployan";
    public var ShorthandFormatControls = "Shorthand Format Controls";
    public var ByzantineMusicalSymbols = "Byzantine Musical Symbols";
    public var MusicalSymbols = "Musical Symbols";
    public var AncientGreekMusicalNotation = "Ancient Greek Musical Notation";
    public var TaiXuanJingSymbols = "Tai Xuan Jing Symbols";
    public var CountingRodNumerals = "Counting Rod Numerals";
    public var MathematicalAlphanumericSymbols = "Mathematical Alphanumeric Symbols";
    public var SuttonSignWriting = "Sutton SignWriting";
    public var GlagoliticSupplement = "Glagolitic Supplement";
    public var MendeKikakui = "Mende Kikakui";
    public var Adlam = "Adlam";
    public var ArabicMathematicalAlphabeticSymbols = "Arabic Mathematical Alphabetic Symbols";
    public var MahjongTiles = "Mahjong Tiles";
    public var DominoTiles = "Domino Tiles";
    public var PlayingCards = "Playing Cards";
    public var EnclosedAlphanumericSupplement = "Enclosed Alphanumeric Supplement";
    public var EnclosedIdeographicSupplement = "Enclosed Ideographic Supplement";
    public var MiscellaneousSymbolsAndPictographs = "Miscellaneous Symbols and Pictographs";
    public var Emoticons = "Emoticons";
    public var OrnamentalDingbats = "Ornamental Dingbats";
    public var TransportAndMapSymbols = "Transport and Map Symbols";
    public var AlchemicalSymbols = "Alchemical Symbols";
    public var GeometricShapesExtended = "Geometric Shapes Extended";
    public var SupplementalArrowsC = "Supplemental Arrows-C";
    public var SupplementalSymbolsAndPictographs = "Supplemental Symbols and Pictographs";
    public var CJKUnifiedIdeographsExtensionB = "CJK Unified Ideographs Extension B";
    public var CJKUnifiedIdeographsExtensionC = "CJK Unified Ideographs Extension C";
    public var CJKUnifiedIdeographsExtensionD = "CJK Unified Ideographs Extension D";
    public var CJKUnifiedIdeographsExtensionE = "CJK Unified Ideographs Extension E";
    public var CJKCompatibilityIdeographsSupplement = "CJK Compatibility Ideographs Supplement";
    public var Tags = "Tags";
    public var VariationSelectorsSupplement = "Variation Selectors Supplement";
    public var SupplementaryPrivateUseAreaA = "Supplementary Private Use Area-A";
    public var SupplementaryPrivateUseAreaB = "Supplementary Private Use Area-B";

    public static inline function all():Array<Block> return [
        BasicLatin, 
        Latin1Supplement, 
        LatinExtendedA, 
        LatinExtendedB, 
        IPAExtensions, 
        SpacingModifierLetters, 
        CombiningDiacriticalMarks, 
        GreekAndCoptic, 
        Cyrillic, 
        CyrillicSupplement, 
        Armenian, 
        Hebrew, 
        Arabic, 
        Syriac, 
        ArabicSupplement, 
        Thaana, 
        NKo, 
        Samaritan, 
        Mandaic, 
        ArabicExtendedA, 
        Devanagari, 
        Bengali, 
        Gurmukhi, 
        Gujarati, 
        Oriya, 
        Tamil, 
        Telugu, 
        Kannada, 
        Malayalam, 
        Sinhala, 
        Thai, 
        Lao, 
        Tibetan, 
        Myanmar, 
        Georgian, 
        HangulJamo, 
        Ethiopic, 
        EthiopicSupplement, 
        Cherokee, 
        UnifiedCanadianAboriginalSyllabics, 
        Ogham, 
        Runic, 
        Tagalog, 
        Hanunoo, 
        Buhid, 
        Tagbanwa, 
        Khmer, 
        Mongolian, 
        UnifiedCanadianAboriginalSyllabicsExtended, 
        Limbu, 
        TaiLe, 
        NewTaiLue, 
        KhmerSymbols, 
        Buginese, 
        TaiTham, 
        CombiningDiacriticalMarksExtended, 
        Balinese, 
        Sundanese, 
        Batak, 
        Lepcha, 
        OlChiki, 
        CyrillicExtendedC, 
        SundaneseSupplement, 
        VedicExtensions, 
        PhoneticExtensions, 
        PhoneticExtensionsSupplement, 
        CombiningDiacriticalMarksSupplement, 
        LatinExtendedAdditional, 
        GreekExtended, 
        GeneralPunctuation, 
        SuperscriptsAndSubscripts, 
        CurrencySymbols, 
        CombiningDiacriticalMarksForSymbols, 
        LetterlikeSymbols, 
        NumberForms, 
        Arrows, 
        MathematicalOperators, 
        MiscellaneousTechnical, 
        ControlPictures, 
        OpticalCharacterRecognition, 
        EnclosedAlphanumerics, 
        BoxDrawing, 
        BlockElements, 
        GeometricShapes, 
        MiscellaneousSymbols, 
        Dingbats, 
        MiscellaneousMathematicalSymbolsA, 
        SupplementalArrowsA, 
        BraillePatterns, 
        SupplementalArrowsB, 
        MiscellaneousMathematicalSymbolsB, 
        SupplementalMathematicalOperators, 
        MiscellaneousSymbolsAndArrows, 
        Glagolitic, 
        LatinExtendedC, 
        Coptic, 
        GeorgianSupplement, 
        Tifinagh, 
        EthiopicExtended, 
        CyrillicExtendedA, 
        SupplementalPunctuation, 
        CJKRadicalsSupplement, 
        KangxiRadicals, 
        IdeographicDescriptionCharacters, 
        CJKSymbolsAndPunctuation, 
        Hiragana, 
        Katakana, 
        Bopomofo, 
        HangulCompatibilityJamo, 
        Kanbun, 
        BopomofoExtended, 
        CJKStrokes, 
        KatakanaPhoneticExtensions, 
        EnclosedCJKLettersAndMonths, 
        CJKCompatibility, 
        CJKUnifiedIdeographsExtensionA, 
        YijingHexagramSymbols, 
        CJKUnifiedIdeographs, 
        YiSyllables, 
        YiRadicals, 
        Lisu, 
        Vai, 
        CyrillicExtendedB, 
        Bamum, 
        ModifierToneLetters, 
        LatinExtendedD, 
        SylotiNagri, 
        CommonIndicNumberForms, 
        PhagsPa, 
        Saurashtra, 
        DevanagariExtended, 
        KayahLi, 
        Rejang, 
        HangulJamoExtendedA, 
        Javanese, 
        MyanmarExtendedB, 
        Cham, 
        MyanmarExtendedA, 
        TaiViet, 
        MeeteiMayekExtensions, 
        EthiopicExtendedA, 
        LatinExtendedE, 
        CherokeeSupplement, 
        MeeteiMayek, 
        HangulSyllables, 
        HangulJamoExtendedB, 
        HighSurrogates, 
        HighPrivateUseSurrogates, 
        LowSurrogates, 
        PrivateUseArea, 
        CJKCompatibilityIdeographs, 
        AlphabeticPresentationForms, 
        ArabicPresentationFormsA, 
        VariationSelectors, 
        VerticalForms, 
        CombiningHalfMarks, 
        CJKCompatibilityForms, 
        SmallFormVariants, 
        ArabicPresentationFormsB, 
        HalfwidthAndFullwidthForms, 
        Specials, 
        LinearBSyllabary, 
        LinearBIdeograms, 
        AegeanNumbers, 
        AncientGreekNumbers, 
        AncientSymbols, 
        PhaistosDisc, 
        Lycian, 
        Carian, 
        CopticEpactNumbers, 
        OldItalic, 
        Gothic, 
        OldPermic, 
        Ugaritic, 
        OldPersian, 
        Deseret, 
        Shavian, 
        Osmanya, 
        Osage, 
        Elbasan, 
        CaucasianAlbanian, 
        LinearA, 
        CypriotSyllabary, 
        ImperialAramaic, 
        Palmyrene, 
        Nabataean, 
        Hatran, 
        Phoenician, 
        Lydian, 
        MeroiticHieroglyphs, 
        MeroiticCursive, 
        Kharoshthi, 
        OldSouthArabian, 
        OldNorthArabian, 
        Manichaean, 
        Avestan, 
        InscriptionalParthian, 
        InscriptionalPahlavi, 
        PsalterPahlavi, 
        OldTurkic, 
        OldHungarian, 
        RumiNumeralSymbols, 
        Brahmi, 
        Kaithi, 
        SoraSompeng, 
        Chakma, 
        Mahajani, 
        Sharada, 
        SinhalaArchaicNumbers, 
        Khojki, 
        Multani, 
        Khudawadi, 
        Grantha, 
        Newa, 
        Tirhuta, 
        Siddham, 
        Modi, 
        MongolianSupplement, 
        Takri, 
        Ahom, 
        WarangCiti, 
        PauCinHau, 
        Bhaiksuki, 
        Marchen, 
        Cuneiform, 
        CuneiformNumbersAndPunctuation, 
        EarlyDynasticCuneiform, 
        EgyptianHieroglyphs, 
        AnatolianHieroglyphs, 
        BamumSupplement, 
        Mro, 
        BassaVah, 
        PahawhHmong, 
        Miao, 
        IdeographicSymbolsAndPunctuation, 
        Tangut, 
        TangutComponents, 
        KanaSupplement, 
        Duployan, 
        ShorthandFormatControls, 
        ByzantineMusicalSymbols, 
        MusicalSymbols, 
        AncientGreekMusicalNotation, 
        TaiXuanJingSymbols, 
        CountingRodNumerals, 
        MathematicalAlphanumericSymbols, 
        SuttonSignWriting, 
        GlagoliticSupplement, 
        MendeKikakui, 
        Adlam, 
        ArabicMathematicalAlphabeticSymbols, 
        MahjongTiles, 
        DominoTiles, 
        PlayingCards, 
        EnclosedAlphanumericSupplement, 
        EnclosedIdeographicSupplement, 
        MiscellaneousSymbolsAndPictographs, 
        Emoticons, 
        OrnamentalDingbats, 
        TransportAndMapSymbols, 
        AlchemicalSymbols, 
        GeometricShapesExtended, 
        SupplementalArrowsC, 
        SupplementalSymbolsAndPictographs, 
        CJKUnifiedIdeographsExtensionB, 
        CJKUnifiedIdeographsExtensionC, 
        CJKUnifiedIdeographsExtensionD, 
        CJKUnifiedIdeographsExtensionE, 
        CJKCompatibilityIdeographsSupplement, 
        Tags, 
        VariationSelectorsSupplement, 
        SupplementaryPrivateUseAreaA, 
        SupplementaryPrivateUseAreaB, 
    ];

    @:to public inline function asRange():uhx.sys.seri.Range {
        return switch this {
            #if !display
            
            case BasicLatin:
                new Range(0, 127);
            
            case Latin1Supplement:
                new Range(128, 255);
            
            case LatinExtendedA:
                new Range(256, 383);
            
            case LatinExtendedB:
                new Range(384, 591);
            
            case IPAExtensions:
                new Range(592, 687);
            
            case SpacingModifierLetters:
                new Range(688, 767);
            
            case CombiningDiacriticalMarks:
                new Range(768, 879);
            
            case GreekAndCoptic:
                new Range(880, 1023);
            
            case Cyrillic:
                new Range(1024, 1279);
            
            case CyrillicSupplement:
                new Range(1280, 1327);
            
            case Armenian:
                new Range(1328, 1423);
            
            case Hebrew:
                new Range(1424, 1535);
            
            case Arabic:
                new Range(1536, 1791);
            
            case Syriac:
                new Range(1792, 1871);
            
            case ArabicSupplement:
                new Range(1872, 1919);
            
            case Thaana:
                new Range(1920, 1983);
            
            case NKo:
                new Range(1984, 2047);
            
            case Samaritan:
                new Range(2048, 2111);
            
            case Mandaic:
                new Range(2112, 2143);
            
            case ArabicExtendedA:
                new Range(2208, 2303);
            
            case Devanagari:
                new Range(2304, 2431);
            
            case Bengali:
                new Range(2432, 2559);
            
            case Gurmukhi:
                new Range(2560, 2687);
            
            case Gujarati:
                new Range(2688, 2815);
            
            case Oriya:
                new Range(2816, 2943);
            
            case Tamil:
                new Range(2944, 3071);
            
            case Telugu:
                new Range(3072, 3199);
            
            case Kannada:
                new Range(3200, 3327);
            
            case Malayalam:
                new Range(3328, 3455);
            
            case Sinhala:
                new Range(3456, 3583);
            
            case Thai:
                new Range(3584, 3711);
            
            case Lao:
                new Range(3712, 3839);
            
            case Tibetan:
                new Range(3840, 4095);
            
            case Myanmar:
                new Range(4096, 4255);
            
            case Georgian:
                new Range(4256, 4351);
            
            case HangulJamo:
                new Range(4352, 4607);
            
            case Ethiopic:
                new Range(4608, 4991);
            
            case EthiopicSupplement:
                new Range(4992, 5023);
            
            case Cherokee:
                new Range(5024, 5119);
            
            case UnifiedCanadianAboriginalSyllabics:
                new Range(5120, 5759);
            
            case Ogham:
                new Range(5760, 5791);
            
            case Runic:
                new Range(5792, 5887);
            
            case Tagalog:
                new Range(5888, 5919);
            
            case Hanunoo:
                new Range(5920, 5951);
            
            case Buhid:
                new Range(5952, 5983);
            
            case Tagbanwa:
                new Range(5984, 6015);
            
            case Khmer:
                new Range(6016, 6143);
            
            case Mongolian:
                new Range(6144, 6319);
            
            case UnifiedCanadianAboriginalSyllabicsExtended:
                new Range(6320, 6399);
            
            case Limbu:
                new Range(6400, 6479);
            
            case TaiLe:
                new Range(6480, 6527);
            
            case NewTaiLue:
                new Range(6528, 6623);
            
            case KhmerSymbols:
                new Range(6624, 6655);
            
            case Buginese:
                new Range(6656, 6687);
            
            case TaiTham:
                new Range(6688, 6831);
            
            case CombiningDiacriticalMarksExtended:
                new Range(6832, 6911);
            
            case Balinese:
                new Range(6912, 7039);
            
            case Sundanese:
                new Range(7040, 7103);
            
            case Batak:
                new Range(7104, 7167);
            
            case Lepcha:
                new Range(7168, 7247);
            
            case OlChiki:
                new Range(7248, 7295);
            
            case CyrillicExtendedC:
                new Range(7296, 7311);
            
            case SundaneseSupplement:
                new Range(7360, 7375);
            
            case VedicExtensions:
                new Range(7376, 7423);
            
            case PhoneticExtensions:
                new Range(7424, 7551);
            
            case PhoneticExtensionsSupplement:
                new Range(7552, 7615);
            
            case CombiningDiacriticalMarksSupplement:
                new Range(7616, 7679);
            
            case LatinExtendedAdditional:
                new Range(7680, 7935);
            
            case GreekExtended:
                new Range(7936, 8191);
            
            case GeneralPunctuation:
                new Range(8192, 8303);
            
            case SuperscriptsAndSubscripts:
                new Range(8304, 8351);
            
            case CurrencySymbols:
                new Range(8352, 8399);
            
            case CombiningDiacriticalMarksForSymbols:
                new Range(8400, 8447);
            
            case LetterlikeSymbols:
                new Range(8448, 8527);
            
            case NumberForms:
                new Range(8528, 8591);
            
            case Arrows:
                new Range(8592, 8703);
            
            case MathematicalOperators:
                new Range(8704, 8959);
            
            case MiscellaneousTechnical:
                new Range(8960, 9215);
            
            case ControlPictures:
                new Range(9216, 9279);
            
            case OpticalCharacterRecognition:
                new Range(9280, 9311);
            
            case EnclosedAlphanumerics:
                new Range(9312, 9471);
            
            case BoxDrawing:
                new Range(9472, 9599);
            
            case BlockElements:
                new Range(9600, 9631);
            
            case GeometricShapes:
                new Range(9632, 9727);
            
            case MiscellaneousSymbols:
                new Range(9728, 9983);
            
            case Dingbats:
                new Range(9984, 10175);
            
            case MiscellaneousMathematicalSymbolsA:
                new Range(10176, 10223);
            
            case SupplementalArrowsA:
                new Range(10224, 10239);
            
            case BraillePatterns:
                new Range(10240, 10495);
            
            case SupplementalArrowsB:
                new Range(10496, 10623);
            
            case MiscellaneousMathematicalSymbolsB:
                new Range(10624, 10751);
            
            case SupplementalMathematicalOperators:
                new Range(10752, 11007);
            
            case MiscellaneousSymbolsAndArrows:
                new Range(11008, 11263);
            
            case Glagolitic:
                new Range(11264, 11359);
            
            case LatinExtendedC:
                new Range(11360, 11391);
            
            case Coptic:
                new Range(11392, 11519);
            
            case GeorgianSupplement:
                new Range(11520, 11567);
            
            case Tifinagh:
                new Range(11568, 11647);
            
            case EthiopicExtended:
                new Range(11648, 11743);
            
            case CyrillicExtendedA:
                new Range(11744, 11775);
            
            case SupplementalPunctuation:
                new Range(11776, 11903);
            
            case CJKRadicalsSupplement:
                new Range(11904, 12031);
            
            case KangxiRadicals:
                new Range(12032, 12255);
            
            case IdeographicDescriptionCharacters:
                new Range(12272, 12287);
            
            case CJKSymbolsAndPunctuation:
                new Range(12288, 12351);
            
            case Hiragana:
                new Range(12352, 12447);
            
            case Katakana:
                new Range(12448, 12543);
            
            case Bopomofo:
                new Range(12544, 12591);
            
            case HangulCompatibilityJamo:
                new Range(12592, 12687);
            
            case Kanbun:
                new Range(12688, 12703);
            
            case BopomofoExtended:
                new Range(12704, 12735);
            
            case CJKStrokes:
                new Range(12736, 12783);
            
            case KatakanaPhoneticExtensions:
                new Range(12784, 12799);
            
            case EnclosedCJKLettersAndMonths:
                new Range(12800, 13055);
            
            case CJKCompatibility:
                new Range(13056, 13311);
            
            case CJKUnifiedIdeographsExtensionA:
                new Range(13312, 19903);
            
            case YijingHexagramSymbols:
                new Range(19904, 19967);
            
            case CJKUnifiedIdeographs:
                new Range(19968, 40959);
            
            case YiSyllables:
                new Range(40960, 42127);
            
            case YiRadicals:
                new Range(42128, 42191);
            
            case Lisu:
                new Range(42192, 42239);
            
            case Vai:
                new Range(42240, 42559);
            
            case CyrillicExtendedB:
                new Range(42560, 42655);
            
            case Bamum:
                new Range(42656, 42751);
            
            case ModifierToneLetters:
                new Range(42752, 42783);
            
            case LatinExtendedD:
                new Range(42784, 43007);
            
            case SylotiNagri:
                new Range(43008, 43055);
            
            case CommonIndicNumberForms:
                new Range(43056, 43071);
            
            case PhagsPa:
                new Range(43072, 43135);
            
            case Saurashtra:
                new Range(43136, 43231);
            
            case DevanagariExtended:
                new Range(43232, 43263);
            
            case KayahLi:
                new Range(43264, 43311);
            
            case Rejang:
                new Range(43312, 43359);
            
            case HangulJamoExtendedA:
                new Range(43360, 43391);
            
            case Javanese:
                new Range(43392, 43487);
            
            case MyanmarExtendedB:
                new Range(43488, 43519);
            
            case Cham:
                new Range(43520, 43615);
            
            case MyanmarExtendedA:
                new Range(43616, 43647);
            
            case TaiViet:
                new Range(43648, 43743);
            
            case MeeteiMayekExtensions:
                new Range(43744, 43775);
            
            case EthiopicExtendedA:
                new Range(43776, 43823);
            
            case LatinExtendedE:
                new Range(43824, 43887);
            
            case CherokeeSupplement:
                new Range(43888, 43967);
            
            case MeeteiMayek:
                new Range(43968, 44031);
            
            case HangulSyllables:
                new Range(44032, 55215);
            
            case HangulJamoExtendedB:
                new Range(55216, 55295);
            
            case HighSurrogates:
                new Range(55296, 56191);
            
            case HighPrivateUseSurrogates:
                new Range(56192, 56319);
            
            case LowSurrogates:
                new Range(56320, 57343);
            
            case PrivateUseArea:
                new Range(57344, 63743);
            
            case CJKCompatibilityIdeographs:
                new Range(63744, 64255);
            
            case AlphabeticPresentationForms:
                new Range(64256, 64335);
            
            case ArabicPresentationFormsA:
                new Range(64336, 65023);
            
            case VariationSelectors:
                new Range(65024, 65039);
            
            case VerticalForms:
                new Range(65040, 65055);
            
            case CombiningHalfMarks:
                new Range(65056, 65071);
            
            case CJKCompatibilityForms:
                new Range(65072, 65103);
            
            case SmallFormVariants:
                new Range(65104, 65135);
            
            case ArabicPresentationFormsB:
                new Range(65136, 65279);
            
            case HalfwidthAndFullwidthForms:
                new Range(65280, 65519);
            
            case Specials:
                new Range(65520, 65535);
            
            case LinearBSyllabary:
                new Range(65536, 65663);
            
            case LinearBIdeograms:
                new Range(65664, 65791);
            
            case AegeanNumbers:
                new Range(65792, 65855);
            
            case AncientGreekNumbers:
                new Range(65856, 65935);
            
            case AncientSymbols:
                new Range(65936, 65999);
            
            case PhaistosDisc:
                new Range(66000, 66047);
            
            case Lycian:
                new Range(66176, 66207);
            
            case Carian:
                new Range(66208, 66271);
            
            case CopticEpactNumbers:
                new Range(66272, 66303);
            
            case OldItalic:
                new Range(66304, 66351);
            
            case Gothic:
                new Range(66352, 66383);
            
            case OldPermic:
                new Range(66384, 66431);
            
            case Ugaritic:
                new Range(66432, 66463);
            
            case OldPersian:
                new Range(66464, 66527);
            
            case Deseret:
                new Range(66560, 66639);
            
            case Shavian:
                new Range(66640, 66687);
            
            case Osmanya:
                new Range(66688, 66735);
            
            case Osage:
                new Range(66736, 66815);
            
            case Elbasan:
                new Range(66816, 66863);
            
            case CaucasianAlbanian:
                new Range(66864, 66927);
            
            case LinearA:
                new Range(67072, 67455);
            
            case CypriotSyllabary:
                new Range(67584, 67647);
            
            case ImperialAramaic:
                new Range(67648, 67679);
            
            case Palmyrene:
                new Range(67680, 67711);
            
            case Nabataean:
                new Range(67712, 67759);
            
            case Hatran:
                new Range(67808, 67839);
            
            case Phoenician:
                new Range(67840, 67871);
            
            case Lydian:
                new Range(67872, 67903);
            
            case MeroiticHieroglyphs:
                new Range(67968, 67999);
            
            case MeroiticCursive:
                new Range(68000, 68095);
            
            case Kharoshthi:
                new Range(68096, 68191);
            
            case OldSouthArabian:
                new Range(68192, 68223);
            
            case OldNorthArabian:
                new Range(68224, 68255);
            
            case Manichaean:
                new Range(68288, 68351);
            
            case Avestan:
                new Range(68352, 68415);
            
            case InscriptionalParthian:
                new Range(68416, 68447);
            
            case InscriptionalPahlavi:
                new Range(68448, 68479);
            
            case PsalterPahlavi:
                new Range(68480, 68527);
            
            case OldTurkic:
                new Range(68608, 68687);
            
            case OldHungarian:
                new Range(68736, 68863);
            
            case RumiNumeralSymbols:
                new Range(69216, 69247);
            
            case Brahmi:
                new Range(69632, 69759);
            
            case Kaithi:
                new Range(69760, 69839);
            
            case SoraSompeng:
                new Range(69840, 69887);
            
            case Chakma:
                new Range(69888, 69967);
            
            case Mahajani:
                new Range(69968, 70015);
            
            case Sharada:
                new Range(70016, 70111);
            
            case SinhalaArchaicNumbers:
                new Range(70112, 70143);
            
            case Khojki:
                new Range(70144, 70223);
            
            case Multani:
                new Range(70272, 70319);
            
            case Khudawadi:
                new Range(70320, 70399);
            
            case Grantha:
                new Range(70400, 70527);
            
            case Newa:
                new Range(70656, 70783);
            
            case Tirhuta:
                new Range(70784, 70879);
            
            case Siddham:
                new Range(71040, 71167);
            
            case Modi:
                new Range(71168, 71263);
            
            case MongolianSupplement:
                new Range(71264, 71295);
            
            case Takri:
                new Range(71296, 71375);
            
            case Ahom:
                new Range(71424, 71487);
            
            case WarangCiti:
                new Range(71840, 71935);
            
            case PauCinHau:
                new Range(72384, 72447);
            
            case Bhaiksuki:
                new Range(72704, 72815);
            
            case Marchen:
                new Range(72816, 72895);
            
            case Cuneiform:
                new Range(73728, 74751);
            
            case CuneiformNumbersAndPunctuation:
                new Range(74752, 74879);
            
            case EarlyDynasticCuneiform:
                new Range(74880, 75087);
            
            case EgyptianHieroglyphs:
                new Range(77824, 78895);
            
            case AnatolianHieroglyphs:
                new Range(82944, 83583);
            
            case BamumSupplement:
                new Range(92160, 92735);
            
            case Mro:
                new Range(92736, 92783);
            
            case BassaVah:
                new Range(92880, 92927);
            
            case PahawhHmong:
                new Range(92928, 93071);
            
            case Miao:
                new Range(93952, 94111);
            
            case IdeographicSymbolsAndPunctuation:
                new Range(94176, 94207);
            
            case Tangut:
                new Range(94208, 100351);
            
            case TangutComponents:
                new Range(100352, 101119);
            
            case KanaSupplement:
                new Range(110592, 110847);
            
            case Duployan:
                new Range(113664, 113823);
            
            case ShorthandFormatControls:
                new Range(113824, 113839);
            
            case ByzantineMusicalSymbols:
                new Range(118784, 119039);
            
            case MusicalSymbols:
                new Range(119040, 119295);
            
            case AncientGreekMusicalNotation:
                new Range(119296, 119375);
            
            case TaiXuanJingSymbols:
                new Range(119552, 119647);
            
            case CountingRodNumerals:
                new Range(119648, 119679);
            
            case MathematicalAlphanumericSymbols:
                new Range(119808, 120831);
            
            case SuttonSignWriting:
                new Range(120832, 121519);
            
            case GlagoliticSupplement:
                new Range(122880, 122927);
            
            case MendeKikakui:
                new Range(124928, 125151);
            
            case Adlam:
                new Range(125184, 125279);
            
            case ArabicMathematicalAlphabeticSymbols:
                new Range(126464, 126719);
            
            case MahjongTiles:
                new Range(126976, 127023);
            
            case DominoTiles:
                new Range(127024, 127135);
            
            case PlayingCards:
                new Range(127136, 127231);
            
            case EnclosedAlphanumericSupplement:
                new Range(127232, 127487);
            
            case EnclosedIdeographicSupplement:
                new Range(127488, 127743);
            
            case MiscellaneousSymbolsAndPictographs:
                new Range(127744, 128511);
            
            case Emoticons:
                new Range(128512, 128591);
            
            case OrnamentalDingbats:
                new Range(128592, 128639);
            
            case TransportAndMapSymbols:
                new Range(128640, 128767);
            
            case AlchemicalSymbols:
                new Range(128768, 128895);
            
            case GeometricShapesExtended:
                new Range(128896, 129023);
            
            case SupplementalArrowsC:
                new Range(129024, 129279);
            
            case SupplementalSymbolsAndPictographs:
                new Range(129280, 129535);
            
            case CJKUnifiedIdeographsExtensionB:
                new Range(131072, 173791);
            
            case CJKUnifiedIdeographsExtensionC:
                new Range(173824, 177983);
            
            case CJKUnifiedIdeographsExtensionD:
                new Range(177984, 178207);
            
            case CJKUnifiedIdeographsExtensionE:
                new Range(178208, 183983);
            
            case CJKCompatibilityIdeographsSupplement:
                new Range(194560, 195103);
            
            case Tags:
                new Range(917504, 917631);
            
            case VariationSelectorsSupplement:
                new Range(917760, 917999);
            
            case SupplementaryPrivateUseAreaA:
                new Range(983040, 1048575);
            
            case SupplementaryPrivateUseAreaB:
                new Range(1048576, 1114111);
            
            #end
            case _:
                uhx.sys.seri.Range.EMPTY;
        }
    }
}